/*
 * Copyright (C) 2011, Broadcom Corporation
 * All Rights Reserved.
 * 
 * THIS SOFTWARE IS OFFERED "AS IS", AND BROADCOM GRANTS NO WARRANTIES OF ANY
 * KIND, EXPRESS OR IMPLIED, BY STATUTE, COMMUNICATION OR OTHERWISE. BROADCOM
 * SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A SPECIFIC PURPOSE OR NONINFRINGEMENT CONCERNING THIS SOFTWARE.
 *
 * $Id: epivers.h.in,v 13.32.4.1 2010-09-17 00:39:18 Exp $
 *
*/

#ifndef _epivers_h_
#define _epivers_h_

#define	EPI_MAJOR_VERSION	5

#define	EPI_MINOR_VERSION	90

#define	EPI_RC_NUMBER		125

#define	EPI_INCREMENTAL_NUMBER	22

#define EPI_BUILD_NUMBER	2

#define	EPI_VERSION		5, 90, 125, 22

#define	EPI_VERSION_NUM		0x055a7d16

#define EPI_VERSION_DEV		5.90.125

/* Driver Version String, ASCII, 32 chars max */
#define	EPI_VERSION_STR		"5.90.125.22"

#define DRV_VERSION_STR		"3.12"

#endif /* _epivers_h_ */
